### ISSUE TITLE
Cannot import or open Chp 1 archi model

### ISSUE THREAD

**Issue by ericis** [Apress/migrating-to-azure#1]
Cannot import or open Chp 1 archi model

Tried with version 4.2 and 4.4

**Comment by jgarverick** [comment]
Apologies for that.  I have a fix in place and will be merging momentarily.

**Comment by jgarverick** [comment]
Updated with PR#2--please get latest and let me know if you have any further questions!

**Comment by ericis** [comment]
Confirmed @jgarverick . I can open the model and I also appreciate the work you did with DrawIO in `Chapter01/examples/Solution Architecture Views.xml`.

**Comment by jgarverick** [comment]
Thank you!  I appreciate the feedback.
